POST http://localhost:80/save_crag
Content-Type: application/json

{
  "id": "test-crag-1234",
  "name": "Malham Cove",
  "updated": true
}

###

POST http://localhost:80/save_crag
Content-Type: application/json

{
  "test": "ID is missing"
}
