AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  github-actions-with-aws-sam

  Sample SAM Template for github-actions-with-aws-sam

Globals:
  Api:
    Cors:
      AllowMethods: "'POST'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 10

Resources:
  SaveImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: save_image/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Environment:
        Variables:
          BUCKET_NAME: test.data.thegnarlytyke.com
      Events:
        SaveImage:
          Type: Api
          Properties:
            Path: /save_image
            Method: post
          Cors:
            AllowMethods: "'POST'"
            AllowHeaders: "'content-type'"
            AllowOrigin: "'*'"
  SaveDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: save_data/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Environment:
        Variables:
          BUCKET_NAME: test.data.thegnarlytyke.com
      Events:
        SaveImage:
          Type: Api
          Properties:
            Path: /save_data
            Method: post
          Cors:
            AllowMethods: "'POST'"
            AllowHeaders: "'content-type'"
            AllowOrigin: "'*'"

Outputs:
  GnarlyApi:
    Description: "Gnarly API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/gnarly/"
  SaveImageFunction:
    Description: "Save Image Lambda Function ARN"
    Value: !GetAtt SaveImageFunction.Arn
  SaveImageFunctionIamRole:
    Description: "Implicit IAM Role created for SaveImage function"
    Value: !GetAtt SaveImageFunctionRole.Arn
  SaveDataFunction:
    Description: "Save Data Lambda Function ARN"
    Value: !GetAtt SaveDataFunction.Arn
  SaveDataFunctionIamRole:
    Description: "Implicit IAM Role created for SaveData function"
    Value: !GetAtt SaveDataFunctionRole.Arn
