name: Deploy to Amazon S3

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-2
  BUCKET_NAME: thegnarlytyke.com

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up node 
      uses: actions/setup-node@v1

    - name: Install dependencies
      run: npm install
      working-directory: ./server
    
    - name: Run tests
      run: npm test
      working-directory: ./server

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./server/public/ s3://${{ env.BUCKET_NAME }} --delete
