name: Deploy to test

on:
  push:
    branches:
      - main

env:
  FRONT_END_DIR: ./front-end
  AWS_REGION: eu-west-2
  WEB_BUCKET_NAME: test.thegnarlytyke.com

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up node 
      uses: actions/setup-node@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Clean cache
      run: npm cache clean --force
      working-directory: ${{ env.FRONT_END_DIR }}

    - name: Install dependencies
      run: npm install
      working-directory: ${{ env.FRONT_END_DIR }}

    - name: Build
      run: npm run build
      working-directory: ${{ env.FRONT_END_DIR }}

    - name: Run web script unit tests
      run: npm test
      working-directory: ${{ env.FRONT_END_DIR }}

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ${{ env.FRONT_END_DIR }}/public/ s3://${{ env.WEB_BUCKET_NAME }} --exclude "config.json" --delete

    - name: Deploy test config
      run: aws s3 sync ${{ env.FRONT_END_DIR }}/config/test s3://${{ env.WEB_BUCKET_NAME }}
